# This is a new type of object rather then the kubernetes objects we know
# This is the configuration to tell k8s to go to letsencrypt to issue certificate
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
 name: noneedrelax-com-tls
spec:
 secretName: noneedrelax-com
 issuerRef: 
  name: letsencrypt-prod
  kind: ClusterIssuer
 commonName: noneedrelax.com
 # this is like the SAN name. 
 dnsNames:
  - noneedrelax.com
  - www.noneedrelax.com
 acme:
  config: 
   - http01:
      ingressClass: nginx
      # this is for the verification process to letsencrypt
     domains:
      - noneedrelax.com
      - www.noneedrelax.com
