# This is a new type of object rather then the kubernetes objects we know
# This is the configuration to tell k8s to go to letsencrypt to issue certificate
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
 name: letsencrypt-prod
spec:
 acme:
  server: https://acme-v02.api.letsencrypt.org/directory
  email: 'noneedrelax@gmail.com'
  privateKeySecretRef: 
   name: letsencrypt-prod
  http01: {}
